# Corrigindo o tipo de dados de `air_pollution_score`
- 2008: converta de string para float
- 2018: converta de int para float

In [2]:
# carregue os conjuntos de dados
import pandas as pd
import numpy as np

df_08 = pd.read_csv('data_08.csv')
df_18 = pd.read_csv('data_18.csv')
df_08.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 13 columns):
model                   986 non-null object
displ                   986 non-null float64
cyl                     986 non-null int64
trans                   986 non-null object
drive                   986 non-null object
fuel                    986 non-null object
veh_class               986 non-null object
air_pollution_score     986 non-null object
city_mpg                986 non-null object
hwy_mpg                 986 non-null object
cmb_mpg                 986 non-null object
greenhouse_gas_score    986 non-null object
smartway                986 non-null object
dtypes: float64(1), int64(1), object(11)
memory usage: 100.2+ KB

In [6]:
df_08.head(11)

,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,ACURA MDX,3.7,6,Auto-S5,4WD,Gasoline,SUV,7,15,20,17,4,no
1,ACURA RDX,2.3,4,Auto-S5,4WD,Gasoline,SUV,7,17,22,19,5,no
2,ACURA RL,3.5,6,Auto-S5,4WD,Gasoline,midsize car,7,16,24,19,5,no
3,ACURA TL,3.2,6,Auto-S5,2WD,Gasoline,midsize car,7,18,26,21,6,yes
4,ACURA TL,3.5,6,Auto-S5,2WD,Gasoline,midsize car,7,17,26,20,6,yes
5,ACURA TL,3.5,6,Man-6,2WD,Gasoline,midsize car,7,18,27,21,6,yes
6,ACURA TSX,2.4,4,Man-6,2WD,Gasoline,small car,6,19,28,22,6,no
7,ACURA TSX,2.4,4,Auto-S5,2WD,Gasoline,small car,6,20,28,23,7,yes
8,ASTON MARTIN DB9,5.9,12,Man-6,2WD,Gasoline,small car,6,10,16,12,0,no
9,ASTON MARTIN DB9,5.9,12,Auto-S6,2WD,Gasoline,small car,6,11,18,13,1,no
10,ASTON MARTIN DB9 Volante,5.9,12,Man-6,2WD,Gasoline,small car,6,10,16,12,0,no

In [4]:
# tente usar as funções to_numeric ou astype do Pandas para converter a coluna
# air_pollution_score do conjunto de dados de 2008 para float -- isso não vai funcionar
df_08['air_pollution_score'] = df_08['air_pollution_score'].astype(int)

ValueError: invalid literal for int() with base 10: '9.5'

# Resolvendo a questão
Parece que isso não vai ser tão simples quanto converter o tipo de dados. Segundo o erro abaixo, o valor na linha 582 seria "6/4" - vamos dar uma olhada.

In [9]:
df_08.iloc[582]

model                   MERCEDES-BENZ C300
displ                                    3
cyl                                      6
trans                              Auto-L7
drive                                  2WD
fuel                           ethanol/gas
veh_class                        small car
air_pollution_score                    6/4
city_mpg                             13/18
hwy_mpg                              19/25
cmb_mpg                              15/21
greenhouse_gas_score                   7/6
smartway                                no
Name: 582, dtype: object

# Não é só o nível de poluição do ar!
As colunas mpg e os nível de gases de efeito estufa também parecem ter o mesmo problema - talvez seja por isso que todos eles foram salvos como strings! Segundo [este link](http://www.fueleconomy.gov/feg/findacarhelp.shtml#airPollutionScore), que eu encontrei na documentação em PDF:

    "Se um veículo pode operar com mais de um tipo de combustível, uma estimativa é fornecida para cada tipo de combustível."
    
Ahh.. então todos veículos com mais de um tipo de combustível, ou híbridos, como aquele visto acima (que usa etanol E gás) terão uma string que armazena dois valores - um para cada. Isto é um pouco complicado, então eu vou mostrar como fazê-lo com o conjunto de dados de 2008, para você então tentar fazer o mesmo com o conjunto de dados de 2018.

In [11]:
# Primeiro, vamos obter todos os híbridos de 2008
hb_08 = df_08[df_08['fuel'].str.contains('/')]
hb_08

,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
582,MERCEDES-BENZ C300,3.0,6,Auto-L7,2WD,ethanol/gas,small car,6/4,13/18,19/25,15/21,7/6,no

Parece que este conjunto de dados só tem um! O de 2018 tem MUITOS mais - mas não se preocupe - os passos que eu estou fazendo aqui vão funcionar para este também!

In [17]:
# híbridos em 2018
hb_18 = df_18[df_18['fuel'].str.contains('/')]
hb_18

,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
52,BMW 330e,2.0,4,SemiAuto-8,2WD,Gasoline/Electricity,small car,3,28/66,34/78,30/71,10,Yes
78,BMW 530e,2.0,4,SemiAuto-8,2WD,Gasoline/Electricity,small car,7,27/70,31/75,29/72,10,Elite
79,BMW 530e,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,small car,7,27/66,31/68,28/67,10,Elite
92,BMW 740e,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,large car,3,25/62,29/68,27/64,9,Yes
189,CHEVROLET Impala,3.6,6,SemiAuto-6,2WD,Ethanol/Gas,large car,5,14/18,20/28,16/22,4,No
195,CHEVROLET Silverado 15,4.3,6,Auto-6,2WD,Ethanol/Gas,pickup,5,12/18,16/24,14/20,4,No
196,CHEVROLET Silverado 15,4.3,6,Auto-6,4WD,Ethanol/Gas,pickup,5,12/17,15/22,13/19,3,No
197,CHEVROLET Silverado 15,5.3,8,Auto-6,2WD,Ethanol/Gas,pickup,3,12/16,17/23,14/19,3,No
212,CHEVROLET Suburban 1500,5.3,8,Auto-6,2WD,Ethanol/Gas,standard SUV,3,12/16,17/23,14/19,3,No
214,CHEVROLET Suburban 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,standard SUV,3,11/16,15/22,12/18,3,No
216,CHEVROLET Tahoe 1500,5.3,8,Auto-6,2WD,Ethanol/Gas,standard SUV,3,12/16,17/23,14/19,3,No
218,CHEVROLET Tahoe 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,standard SUV,3,11/16,16/22,13/18,3,No
225,CHEVROLET Volt,1.5,4,CVT,2WD,Gasoline/Electricity,small car,3,43/113,42/99,42/106,10,Yes
226,CHEVROLET Volt,1.5,4,CVT,2WD,Gasoline/Electricity,small car,7,43/113,42/99,42/106,10,Elite
227,CHRYSLER 300,3.6,6,Auto-8,2WD,Ethanol/Gas,large car,3,14/19,22/30,17/23,5,No
229,CHRYSLER 300,3.6,6,Auto-8,4WD,Ethanol/Gas,large car,3,13/18,20/27,16/21,4,No
244,DODGE Charger,3.6,6,Auto-8,2WD,Ethanol/Gas,large car,3,14/19,22/30,17/23,5,No
246,DODGE Charger,3.6,6,Auto-8,4WD,Ethanol/Gas,large car,3,13/18,20/27,16/21,4,No
300,FORD Fusion Energi Plug-in Hybrid,2.0,4,CVT,2WD,Gasoline/Electricity,midsize car,7,43/102,41/91,42/97,10,Elite
326,GMC Sierra 15,4.3,6,Auto-6,2WD,Ethanol/Gas,pickup,5,12/18,16/24,14/20,4,No
327,GMC Sierra 15,4.3,6,Auto-6,4WD,Ethanol/Gas,pickup,5,12/17,15/22,13/19,3,No
328,GMC Sierra 15,5.3,8,Auto-6,2WD,Ethanol/Gas,pickup,3,12/16,17/23,14/19,3,No
345,GMC Yukon 1500,5.3,8,Auto-6,2WD,Ethanol/Gas,standard SUV,3,12/16,17/23,14/19,3,No
347,GMC Yukon 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,standard SUV,3,11/16,16/22,13/18,3,No
351,GMC Yukon 1500 XL,5.3,8,Auto-6,2WD,Ethanol/Gas,standard SUV,3,12/16,17/23,14/19,3,No
354,GMC Yukon XL 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,standard SUV,3,11/16,15/22,12/18,3,No
442,JEEP Cherokee,2.4,4,Auto-9,2WD,Ethanol/Gas,small SUV,3,15/21,22/30,18/25,5,No
444,JEEP Cherokee,2.4,4,Auto-9,4WD,Ethanol/Gas,small SUV,3,14/21,21/28,17/23,5,No
462,KARMA Revero,2.0,4,Auto-1,2WD,Gasoline/Electricity,small car,1,20/59,21/61,20/60,10,No
571,MERCEDES-BENZ CLA250 4Matic,2.0,4,AutoMan-7,4WD,Ethanol/Gas,small car,5,17/24,24/32,20/27,6,No
578,MERCEDES-BENZ GLA250 4Matic,2.0,4,AutoMan-7,4WD,Ethanol/Gas,small SUV,5,17/23,23/31,19/26,5,No
584,MERCEDES-BENZ GLE350 4Matic,3.5,6,Auto-7,4WD,Ethanol/Gas,standard SUV,3,13/18,17/22,14/19,3,No
616,MINI Cooper SE Countryman All4,1.5,3,SemiAuto-6,4WD,Gasoline/Electricity,midsize car,3,28/63,27/66,27/65,9,Yes
742,TOYOTA Sequoia FFV,5.7,8,SemiAuto-6,4WD,Ethanol/Gas,standard SUV,5,9/13,13/17,10/14,1,No
747,TOYOTA Tundra FFV,5.7,8,SemiAuto-6,4WD,Ethanol/Gas,pickup,5,9/13,12/17,10/15,2,No
777,VOLVO S90,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,midsize car,7,26/70,33/72,29/71,10,Elite
789,VOLVO XC 60,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,small SUV,7,26/60,28/58,26/59,10,Elite
793,VOLVO XC 90,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,standard SUV,7,26/63,30/61,27/62,10,Elite

Vamos pegar cada linha que contém um carro híbrido e dividí-la em duas novas linhas - uma com os valores do primeiro tipo de combustível (valores antes da "/") e outra com os valores do segundo tipo de combustível (valores depois da "/"). Vamos separá-los com dois dataframes!

In [21]:
# crie duas cópias do dataframe com híbridos de 2008
df1 = hb_08.copy()  # data on first fuel type of each hybrid vehicle
df2 = hb_08.copy()  # data on second fuel type of each hybrid vehicle

# Cada um deve se parecer com isto
df1

,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
582,MERCEDES-BENZ C300,3.0,6,Auto-L7,2WD,ethanol/gas,small car,6/4,13/18,19/25,15/21,7/6,no

Para a próxima parte, vamos usar a função apply do Pandas. Veja a documentação [aqui](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.apply.html).

In [24]:
# colunas que devem ser divididas por "/"
split_columns = ['fuel', 'air_pollution_score', 'city_mpg', 'hwy_mpg', 'cmb_mpg', 'greenhouse_gas_score']

# aplique a função split para cada coluna de cada cópia do dataframe
for c in split_columns:
    df1[c] = df1[c].apply(lambda x: x.split("/")[0])
    df2[c] = df2[c].apply(lambda x: x.split("/")[1])

In [25]:
# este dataframe armazena informações sobre o PRIMEIRO tipo de combustível do híbrido
# i.e. os valores antes das "/"s
df1

,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
582,MERCEDES-BENZ C300,3.0,6,Auto-L7,2WD,ethanol,small car,6,13,19,15,7,no

In [26]:
# este dataframe armazena informações sobre o SEGUNDO tipo de combustível do híbrido
# i.e. os valores depois das "/"s
df2

,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
582,MERCEDES-BENZ C300,3.0,6,Auto-L7,2WD,gas,small car,4,18,25,21,6,no

In [27]:
# combine dataframes para adicionar ao dataframe original
new_rows = df1.append(df2)

# agora temos linhas separadas para cada tipo de combustível de cada veículo!
new_rows

,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
582,MERCEDES-BENZ C300,3.0,6,Auto-L7,2WD,ethanol,small car,6,13,19,15,7,no
582,MERCEDES-BENZ C300,3.0,6,Auto-L7,2WD,gas,small car,4,18,25,21,6,no

In [28]:
# descarte as linhas originais que continham híbridos
df_08.drop(hb_08.index, inplace=True)

# adicione as novas linhas separadas
df_08 = df_08.append(new_rows, ignore_index=True)

In [29]:
# verifique se todas linhas originais com híbridos, que continham "/"s, sumiram
df_08[df_08['fuel'].str.contains('/')]

Empty DataFrame
Columns: [model, displ, cyl, trans, drive, fuel, veh_class, air_pollution_score, city_mpg, hwy_mpg, cmb_mpg, greenhouse_gas_score, smartway]
Index: []

In [30]:
df_08.shape

(987, 13)

# Repita este processo para o conjunto de dados de 2018

In [31]:
# crie duas cópias do dataframe com híbridos de 2018, hb_18
df1 = hb_18.copy()
df2 = hb_18.copy()

### Divida valores para `fuel`, `city_mpg`, `hwy_mpg`, `cmb_mpg`
Você não precisa dividir as colunas `air_pollution_score` ou `greenhouse_gas_score` aqui porque estas colunas já são ints no conjunto de dados de 2018.

In [32]:
# lista de colunas que devem ser divididas
split_columns = ['fuel', 'city_mpg', 'hwy_mpg', 'cmb_mpg']

# aplique a função split para cada coluna de cada cópia do dataframe
for c in split_columns:
    df1[c] = df1[c].apply(lambda x:x.split("/")[0])
    df2[c] = df2[c].apply(lambda x:x.split("/")[1])

In [33]:
df1

,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
52,BMW 330e,2.0,4,SemiAuto-8,2WD,Gasoline,small car,3,28,34,30,10,Yes
78,BMW 530e,2.0,4,SemiAuto-8,2WD,Gasoline,small car,7,27,31,29,10,Elite
79,BMW 530e,2.0,4,SemiAuto-8,4WD,Gasoline,small car,7,27,31,28,10,Elite
92,BMW 740e,2.0,4,SemiAuto-8,4WD,Gasoline,large car,3,25,29,27,9,Yes
189,CHEVROLET Impala,3.6,6,SemiAuto-6,2WD,Ethanol,large car,5,14,20,16,4,No
195,CHEVROLET Silverado 15,4.3,6,Auto-6,2WD,Ethanol,pickup,5,12,16,14,4,No
196,CHEVROLET Silverado 15,4.3,6,Auto-6,4WD,Ethanol,pickup,5,12,15,13,3,No
197,CHEVROLET Silverado 15,5.3,8,Auto-6,2WD,Ethanol,pickup,3,12,17,14,3,No
212,CHEVROLET Suburban 1500,5.3,8,Auto-6,2WD,Ethanol,standard SUV,3,12,17,14,3,No
214,CHEVROLET Suburban 1500,5.3,8,Auto-6,4WD,Ethanol,standard SUV,3,11,15,12,3,No
216,CHEVROLET Tahoe 1500,5.3,8,Auto-6,2WD,Ethanol,standard SUV,3,12,17,14,3,No
218,CHEVROLET Tahoe 1500,5.3,8,Auto-6,4WD,Ethanol,standard SUV,3,11,16,13,3,No
225,CHEVROLET Volt,1.5,4,CVT,2WD,Gasoline,small car,3,43,42,42,10,Yes
226,CHEVROLET Volt,1.5,4,CVT,2WD,Gasoline,small car,7,43,42,42,10,Elite
227,CHRYSLER 300,3.6,6,Auto-8,2WD,Ethanol,large car,3,14,22,17,5,No
229,CHRYSLER 300,3.6,6,Auto-8,4WD,Ethanol,large car,3,13,20,16,4,No
244,DODGE Charger,3.6,6,Auto-8,2WD,Ethanol,large car,3,14,22,17,5,No
246,DODGE Charger,3.6,6,Auto-8,4WD,Ethanol,large car,3,13,20,16,4,No
300,FORD Fusion Energi Plug-in Hybrid,2.0,4,CVT,2WD,Gasoline,midsize car,7,43,41,42,10,Elite
326,GMC Sierra 15,4.3,6,Auto-6,2WD,Ethanol,pickup,5,12,16,14,4,No
327,GMC Sierra 15,4.3,6,Auto-6,4WD,Ethanol,pickup,5,12,15,13,3,No
328,GMC Sierra 15,5.3,8,Auto-6,2WD,Ethanol,pickup,3,12,17,14,3,No
345,GMC Yukon 1500,5.3,8,Auto-6,2WD,Ethanol,standard SUV,3,12,17,14,3,No
347,GMC Yukon 1500,5.3,8,Auto-6,4WD,Ethanol,standard SUV,3,11,16,13,3,No
351,GMC Yukon 1500 XL,5.3,8,Auto-6,2WD,Ethanol,standard SUV,3,12,17,14,3,No
354,GMC Yukon XL 1500,5.3,8,Auto-6,4WD,Ethanol,standard SUV,3,11,15,12,3,No
442,JEEP Cherokee,2.4,4,Auto-9,2WD,Ethanol,small SUV,3,15,22,18,5,No
444,JEEP Cherokee,2.4,4,Auto-9,4WD,Ethanol,small SUV,3,14,21,17,5,No
462,KARMA Revero,2.0,4,Auto-1,2WD,Gasoline,small car,1,20,21,20,10,No
571,MERCEDES-BENZ CLA250 4Matic,2.0,4,AutoMan-7,4WD,Ethanol,small car,5,17,24,20,6,No
578,MERCEDES-BENZ GLA250 4Matic,2.0,4,AutoMan-7,4WD,Ethanol,small SUV,5,17,23,19,5,No
584,MERCEDES-BENZ GLE350 4Matic,3.5,6,Auto-7,4WD,Ethanol,standard SUV,3,13,17,14,3,No
616,MINI Cooper SE Countryman All4,1.5,3,SemiAuto-6,4WD,Gasoline,midsize car,3,28,27,27,9,Yes
742,TOYOTA Sequoia FFV,5.7,8,SemiAuto-6,4WD,Ethanol,standard SUV,5,9,13,10,1,No
747,TOYOTA Tundra FFV,5.7,8,SemiAuto-6,4WD,Ethanol,pickup,5,9,12,10,2,No
777,VOLVO S90,2.0,4,SemiAuto-8,4WD,Gasoline,midsize car,7,26,33,29,10,Elite
789,VOLVO XC 60,2.0,4,SemiAuto-8,4WD,Gasoline,small SUV,7,26,28,26,10,Elite
793,VOLVO XC 90,2.0,4,SemiAuto-8,4WD,Gasoline,standard SUV,7,26,30,27,10,Elite

In [34]:
df2

,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
52,BMW 330e,2.0,4,SemiAuto-8,2WD,Electricity,small car,3,66,78,71,10,Yes
78,BMW 530e,2.0,4,SemiAuto-8,2WD,Electricity,small car,7,70,75,72,10,Elite
79,BMW 530e,2.0,4,SemiAuto-8,4WD,Electricity,small car,7,66,68,67,10,Elite
92,BMW 740e,2.0,4,SemiAuto-8,4WD,Electricity,large car,3,62,68,64,9,Yes
189,CHEVROLET Impala,3.6,6,SemiAuto-6,2WD,Gas,large car,5,18,28,22,4,No
195,CHEVROLET Silverado 15,4.3,6,Auto-6,2WD,Gas,pickup,5,18,24,20,4,No
196,CHEVROLET Silverado 15,4.3,6,Auto-6,4WD,Gas,pickup,5,17,22,19,3,No
197,CHEVROLET Silverado 15,5.3,8,Auto-6,2WD,Gas,pickup,3,16,23,19,3,No
212,CHEVROLET Suburban 1500,5.3,8,Auto-6,2WD,Gas,standard SUV,3,16,23,19,3,No
214,CHEVROLET Suburban 1500,5.3,8,Auto-6,4WD,Gas,standard SUV,3,16,22,18,3,No
216,CHEVROLET Tahoe 1500,5.3,8,Auto-6,2WD,Gas,standard SUV,3,16,23,19,3,No
218,CHEVROLET Tahoe 1500,5.3,8,Auto-6,4WD,Gas,standard SUV,3,16,22,18,3,No
225,CHEVROLET Volt,1.5,4,CVT,2WD,Electricity,small car,3,113,99,106,10,Yes
226,CHEVROLET Volt,1.5,4,CVT,2WD,Electricity,small car,7,113,99,106,10,Elite
227,CHRYSLER 300,3.6,6,Auto-8,2WD,Gas,large car,3,19,30,23,5,No
229,CHRYSLER 300,3.6,6,Auto-8,4WD,Gas,large car,3,18,27,21,4,No
244,DODGE Charger,3.6,6,Auto-8,2WD,Gas,large car,3,19,30,23,5,No
246,DODGE Charger,3.6,6,Auto-8,4WD,Gas,large car,3,18,27,21,4,No
300,FORD Fusion Energi Plug-in Hybrid,2.0,4,CVT,2WD,Electricity,midsize car,7,102,91,97,10,Elite
326,GMC Sierra 15,4.3,6,Auto-6,2WD,Gas,pickup,5,18,24,20,4,No
327,GMC Sierra 15,4.3,6,Auto-6,4WD,Gas,pickup,5,17,22,19,3,No
328,GMC Sierra 15,5.3,8,Auto-6,2WD,Gas,pickup,3,16,23,19,3,No
345,GMC Yukon 1500,5.3,8,Auto-6,2WD,Gas,standard SUV,3,16,23,19,3,No
347,GMC Yukon 1500,5.3,8,Auto-6,4WD,Gas,standard SUV,3,16,22,18,3,No
351,GMC Yukon 1500 XL,5.3,8,Auto-6,2WD,Gas,standard SUV,3,16,23,19,3,No
354,GMC Yukon XL 1500,5.3,8,Auto-6,4WD,Gas,standard SUV,3,16,22,18,3,No
442,JEEP Cherokee,2.4,4,Auto-9,2WD,Gas,small SUV,3,21,30,25,5,No
444,JEEP Cherokee,2.4,4,Auto-9,4WD,Gas,small SUV,3,21,28,23,5,No
462,KARMA Revero,2.0,4,Auto-1,2WD,Electricity,small car,1,59,61,60,10,No
571,MERCEDES-BENZ CLA250 4Matic,2.0,4,AutoMan-7,4WD,Gas,small car,5,24,32,27,6,No
578,MERCEDES-BENZ GLA250 4Matic,2.0,4,AutoMan-7,4WD,Gas,small SUV,5,23,31,26,5,No
584,MERCEDES-BENZ GLE350 4Matic,3.5,6,Auto-7,4WD,Gas,standard SUV,3,18,22,19,3,No
616,MINI Cooper SE Countryman All4,1.5,3,SemiAuto-6,4WD,Electricity,midsize car,3,63,66,65,9,Yes
742,TOYOTA Sequoia FFV,5.7,8,SemiAuto-6,4WD,Gas,standard SUV,5,13,17,14,1,No
747,TOYOTA Tundra FFV,5.7,8,SemiAuto-6,4WD,Gas,pickup,5,13,17,15,2,No
777,VOLVO S90,2.0,4,SemiAuto-8,4WD,Electricity,midsize car,7,70,72,71,10,Elite
789,VOLVO XC 60,2.0,4,SemiAuto-8,4WD,Electricity,small SUV,7,60,58,59,10,Elite
793,VOLVO XC 90,2.0,4,SemiAuto-8,4WD,Electricity,standard SUV,7,63,61,62,10,Elite

In [35]:
# combine os dois dataframes
new_rows = df1.append(df2)

# descarte cada linha original que continha híbridos no dataframe original de 2018
# faça isso usando a função drop do Pandas com o índice do hb_18
df_18.drop(hb_18.index, inplace=True)

# anexe new_rows a df_18
df_18 = df_18.append(new_rows, ignore_index=True)

In [36]:
# verifique se elas sumiram
df_18[df_18['fuel'].str.contains('/')]

Empty DataFrame
Columns: [model, displ, cyl, trans, drive, fuel, veh_class, air_pollution_score, city_mpg, hwy_mpg, cmb_mpg, greenhouse_gas_score, smartway]
Index: []

In [37]:
df_18.shape

(832, 13)

### Agora podemos confortavelmente continuar as mudanças necessárias para `air_pollution_score`! Aqui vão elas novamente:
- 2008: converta de string para float
- 2018: converta de int para float

In [42]:
# converta a coluna de poluição do ar de 2008 de string para float
df_08['air_pollution_score'] = df_08['air_pollution_score'].astype(float)
df_08.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987 entries, 0 to 986
Data columns (total 13 columns):
model                   987 non-null object
displ                   987 non-null float64
cyl                     987 non-null int64
trans                   987 non-null object
drive                   987 non-null object
fuel                    987 non-null object
veh_class               987 non-null object
air_pollution_score     987 non-null float64
city_mpg                987 non-null object
hwy_mpg                 987 non-null object
cmb_mpg                 987 non-null object
greenhouse_gas_score    987 non-null object
smartway                987 non-null object
dtypes: float64(2), int64(1), object(10)
memory usage: 100.3+ KB

In [43]:
# converta a coluna de poluição do ar de 2018 de int to float
df_18['air_pollution_score'] = df_18['air_pollution_score'].astype(float)
df_18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 832 entries, 0 to 831
Data columns (total 13 columns):
model                   832 non-null object
displ                   832 non-null float64
cyl                     832 non-null int64
trans                   832 non-null object
drive                   832 non-null object
fuel                    832 non-null object
veh_class               832 non-null object
air_pollution_score     832 non-null float64
city_mpg                832 non-null object
hwy_mpg                 832 non-null object
cmb_mpg                 832 non-null object
greenhouse_gas_score    832 non-null int64
smartway                832 non-null object
dtypes: float64(2), int64(2), object(9)
memory usage: 84.6+ KB

In [44]:
df_08.to_csv('data_08.csv', index=False)
df_18.to_csv('data_18.csv', index=False)